# Câu hỏi 1

In [1]:
import numpy as np

def compute_vector_length(vector):
    return np.sqrt(np.sum(vector**2))

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


# Câu hỏi 2

Công thức: $\vec{v1} \cdot \vec{v2} = \sum_{i=0}^{n-1} v1[i] \times v2[i]$

In [2]:
import numpy as np

def compute_dot_product(vector1, vector2):
    return np.dot(vector1, vector2)

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


# Câu hỏi 3

Công thức: $\text{result}[i] = \sum_{j=0}^{n-1} \text{matrix}[i][j] \times \text{vector}[j]$

In [3]:
import numpy as np

def matrix_multi_vector(matrix, vector):
    return np.dot(matrix, vector)

matrix = np.array([[-1, 1, 1], [0, -4, 9]])
vector = np.array([0, 2, 1])
result = matrix_multi_vector(matrix, vector)
print(result)

[3 1]


# Câu hỏi 4

In [4]:
import numpy as np

def matrix_multi_matrix(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


# Câu hỏi 5

In [5]:
import numpy as np

def compute_cosine(v1, v2):
    dot_product = np.dot(v1, v2)
    norm_v1 = np.sqrt(np.sum(v1**2))
    norm_v2 = np.sqrt(np.sum(v2**2))
    return dot_product / (norm_v1 * norm_v2)

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

0.577


# Câu hỏi 6

In [6]:
import numpy as np
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


# Câu hỏi 7

In [7]:
import numpy as np
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Câu hỏi 8

In [8]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
print(arr1)
arr2 = np.ones((2, 5), dtype=int)
print(arr2)
c = np.concatenate([arr1, arr2], axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Câu hỏi 9

In [9]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
print(arr1)
arr2 = np.ones((2, 5), dtype=int)
print(arr2)
c = np.concatenate([arr1, arr2], axis=1)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# Câu hỏi 10

In [10]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 6  9 10]


# Câu hỏi 11

In [11]:
!gdown 1KAZQVg40mG0vuEdC4HbjkDdms_brf2bW
import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread('./dog.jpeg')

Downloading...
From: https://drive.google.com/uc?id=1KAZQVg40mG0vuEdC4HbjkDdms_brf2bW
To: d:\GitHub\AIO_Module_II\Homework\dog.jpeg

  0%|          | 0.00/33.7k [00:00<?, ?B/s]
100%|██████████| 33.7k/33.7k [00:00<00:00, 13.2MB/s]


# Câu hỏi 11

In [12]:
# *********** Your code here ***********
# Sử dụng công thức Lightness: (max(R,G,B) + min(R,G,B))/2
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2

print(gray_img_01[0, 0])

102.5


# Câu hỏi 12

In [13]:
# *********** Your code here ***********
# Sử dụng công thức Average: (R+G+B)/3
gray_img_02 = np.sum(img, axis=2) / 3

print(gray_img_02[0, 0])

107.66666666666667


# Câu hỏi 13

In [14]:
# *********** Your code here ***********
# Sử dụng công thức Luminosity: 0.21*R + 0.72*G + 0.07*B
gray_img_03 = (img[:, :, 0] * 0.21 + img[:, :, 1] * 0.72 + img[:, :, 2] * 0.07)

print(gray_img_03[0, 0])

126.22999999999999


# **Background Subtraction**

In [15]:
!gdown 1QAXardZbIByfehzshQvbw4ByxiTC1ztU
!gdown 1DpKi1rgqHgAEAA0Cx2RWZs_7yWv5bv2T
!gdown 1DYO_g9_NPjwVOxXNZ4upEWjfHBm4byqU

Downloading...
From: https://drive.google.com/uc?id=1QAXardZbIByfehzshQvbw4ByxiTC1ztU
To: d:\GitHub\AIO_Module_II\Homework\Object.png

  0%|          | 0.00/51.0k [00:00<?, ?B/s]
100%|██████████| 51.0k/51.0k [00:00<00:00, 11.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DpKi1rgqHgAEAA0Cx2RWZs_7yWv5bv2T
To: d:\GitHub\AIO_Module_II\Homework\GreenBackground.png

  0%|          | 0.00/5.51k [00:00<?, ?B/s]
100%|██████████| 5.51k/5.51k [00:00<00:00, 4.96MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DYO_g9_NPjwVOxXNZ4upEWjfHBm4byqU
To: d:\GitHub\AIO_Module_II\Homework\NewBackground.jpg

  0%|          | 0.00/64.3k [00:00<?, ?B/s]
100%|██████████| 64.3k/64.3k [00:00<00:00, 1.72MB/s]


In [16]:
import cv2

bg1_image = cv2.imread('GreenBackground.png', 1)
ob_image = cv2.imread('Object.png', 1)
bg2_image = cv2.imread('NewBackground.jpg', 1)
print(bg1_image.shape)
print(ob_image.shape)
print(bg2_image.shape)

(381, 678, 3)
(381, 678, 3)
(408, 612, 3)


In [17]:
IMG_SIZE = (678, 381)
bg1_image = cv2.resize(bg1_image, IMG_SIZE)
ob_image = cv2.resize(ob_image, IMG_SIZE)
bg2_image = cv2.resize(bg2_image, IMG_SIZE)
print(bg1_image.shape)
print(ob_image.shape)
print(bg2_image.shape)

(381, 678, 3)
(381, 678, 3)
(381, 678, 3)


In [18]:
import cv2
def compute_difference(bg_img, input_img):
    return np.abs(bg_img - input_img).mean(axis=2)

difference_single_channel = compute_difference(
    bg1_image, ob_image
)
print(difference_single_channel.shape)
cv2.imshow('Difference', difference_single_channel.astype(np.uint8))
cv2.waitKey(0)  # Chờ bấm phím bất kỳ
cv2.destroyAllWindows()  # Đóng cửa sổ

(381, 678)


In [19]:
def compute_binary_mask(difference_single_channel):
    difference_binary = np.where(
        difference_single_channel >= 15, 255, 0
    )
    difference_binary = np.stack(
        (difference_binary,)*3, axis=-1
    )
    return difference_binary

binary_mask = compute_binary_mask(
    difference_single_channel
)
cv2.imshow('Binary Mask', binary_mask.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
def replace_background(bg1_image, bg2_image, ob_image):
    difference_single_channel = compute_difference(bg1_image,ob_image)
    binary_mask = compute_binary_mask(difference_single_channel)

    output = np.where(binary_mask==255, ob_image, bg2_image)

    return output

output = replace_background(bg1_image, bg2_image, ob_image)

cv2.imshow('Output', output.astype(np.uint8))
cv2.waitKey(0)
cv2.destroyAllWindows()

# Câu hỏi 14

In [21]:
import numpy as np
import cv2
bg1_image = cv2.imread('GreenBackground.png', 1)
bg1_image = cv2.resize(bg1_image, (678, 381))
ob_image = cv2.imread('Object.png', 1)
ob_image = cv2.resize(ob_image, (678, 381))
def compute_difference(bg_img, input_img):
    return np.abs(bg_img - input_img).mean(axis=2)
difference_single_channel = compute_difference(bg1_image, ob_image)
print(difference_single_channel.shape)

(381, 678)


# Câu hỏi 15

In [ ]:
import numpy as np
import cv2
def compute_binary_mask(difference_single_channel):
    binary_mask = (difference_single_channel > 50).astype(np.uint8) * 255
    return binary_mask
difference_single_channel = np.random.rand(678, 381) * 100
binary_mask = compute_binary_mask(difference_single_channel)
print(binary_mask.dtype)

uint8


# Câu hỏi 16

In [23]:
!gdown 1YF4WkCaaGYd2Zm-PNoLa2A2tFf3e64ci

Downloading...
From: https://drive.google.com/uc?id=1YF4WkCaaGYd2Zm-PNoLa2A2tFf3e64ci
To: d:\GitHub\AIO_Module_II\Homework\advertising.csv

  0%|          | 0.00/4.06k [00:00<?, ?B/s]
100%|██████████| 4.06k/4.06k [00:00<00:00, 4.06MB/s]


In [24]:
import pandas as pd

df = pd.read_csv('./advertising.csv')
data = df.to_numpy()
data[:5]

array([[230.1,  37.8,  69.2,  22.1],
       [ 44.5,  39.3,  45.1,  10.4],
       [ 17.2,  45.9,  69.3,  12. ],
       [151.5,  41.3,  58.5,  16.5],
       [180.8,  10.8,  58.4,  17.9]])

In [31]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [26]:
import pandas as pd
import numpy as np
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()
sales = data[:, -1]
max_value = np.max(sales)
max_index = np.argmax(sales)
print(f"Max: {max_value} - Index: {max_index}")

Max: 27.0 - Index: 175


# Câu hỏi 17

In [27]:
import pandas as pd
import numpy as np
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()
tv = data[:, 0]
mean_tv = np.mean(tv)
print(mean_tv)

147.0425


# Câu hỏi 18

In [29]:
import pandas as pd
import numpy as np
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()
sales = data[:, -1]
count = np.count_nonzero(sales >= 20)
print(count)

40


# Câu hỏi 19

In [32]:
import pandas as pd
import numpy as np
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()
sales = data[:, -1]
radio = data[:, 1]
mean_radio = np.mean(radio[sales >= 15])
print(mean_radio)

26.22293577981651


# Câu hỏi 20

In [33]:
import pandas as pd
import numpy as np
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()
sales = data[:, -1]
newspaper = data[:, 2]
mean_newspaper = np.mean(newspaper)
sum_sales = np.sum(sales[newspaper > mean_newspaper])
print(sum_sales)

1405.1
